# Generated by Django 4.1.7 on 2023-04-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.UUIDField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'screens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('column', models.CharField(max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screens.screenmodel')),
            ],
            options={
                'db_table': 'screens_seat',
                'managed': True,
                'unique_together': {('screen_id', 'column', 'row')},
            },
        ),
    ]
