# Generated by Django 4.1.7 on 2023-04-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'screens_movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShowsModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screens.moviemodel')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screens.screenmodel')),
            ],
            options={
                'db_table': 'screens_shows',
                'managed': True,
            },
        ),
    ]
