# Generated by Django 4.1.7 on 2023-04-02 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_showsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsmodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
