# Generated by Django 4.1.7 on 2023-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0006_alter_showsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenmodel',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
