# Generated by Django 4.1.7 on 2023-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('show_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('seat_id', models.UUIDField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'managed': True,
            },
        ),
    ]
