# Generated by Django 4.1.7 on 2023-04-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingmodel_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingmodel',
            unique_together={('show_id', 'seat_id')},
        ),
    ]
