# Generated by Django 4.1.7 on 2023-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'booked'), (2, 'cancelled'), (3, 'completed')], default=1),
        ),
    ]
